quarkus:
  http:
    port: 9092
  datasource:
    jdbc:
      url: jdbc:h2:mem:default
  hibernate-orm:
    database:
      generation: drop-and-create

mp:
  messaging:
    incoming:
      requests:
        connector: smallrye-rabbitmq
        queue:
          name: order-requests
        exchange:
          name: order
#    outgoing:
#      order:
#        connector: smallrye-rabbitmq
#        exchange:
#          name: order

