quarkus:
  http:
    port: 9092
mp:
  messaging:
    incoming:
      requests:
        connector: smallrye-rabbitmq
        queue:
          name: quote-requests
    outgoing:
      quotes:
        connector: smallrye-rabbitmq
